### ISSUE TITLE
Alias issues on join

### ISSUE THREAD

**Issue by johanols** [roapi/roapi#78] opened 2021-09-18 10:25 UTC
I have a simple setup with the following configuration and tables:

**roapi.yml**
```
addr: 0.0.0.0:8080
tables:
  - name: "countries"
    uri: "countries.csv"

  - name: "cities"
    uri: "cities.csv"
```

**countries.csv**
```
ID,COUNTRY
1,Germany
2,Sweden
3,Japan
```

**cities.csv**
```
ID,CITY,COUNTRY_ID
1,Hamburg,1
2,Stockholm,2
3,Osaka,3
4,Berlin,1
5,Göteborg,2
6,Tokyo,3
7,Kyoto,3
```

If I then perform the following `JOIN` request without any issues:

```
$ curl -X POST -H 'Accept: application/csv' -d "SELECT c1.CITY, c2.COUNTRY FROM cities AS c1 JOIN countries AS c2 ON c1.COUNTRY_ID = c2.ID" http://127.0.0.1:8080/api/sql

CITY,COUNTRY
Stockholm,Sweden
Göteborg,Sweden
Osaka,Japan
Tokyo,Japan
Kyoto,Japan
Hamburg,Germany
Berlin,Germany
```

But if I then try to additionally select the city `ID` things doesn't goes so well:

```
$ curl -X POST -H 'Accept: application/json' -d "SELECT c1.ID, c1.CITY, c2.COUNTRY FROM cities AS c1 JOIN countries AS c2 ON c1.COUNTRY_ID = c2.ID" http://127.0.0.1:8080/api/sql

{"code":400,"error":"query_execution","message":"Failed to execute query: Error during planning: The left schema and the right schema have the following columns with the same name without being on the ON statement: {Column { name: \"ID\", index: 0 }}. Consider aliasing them."}%
```

To me this seems as if the aliasing is not working as expected. I would expect the query engine to be able to distinguish between those two fields since I've aliased the to tables (`c1` and `c2` respectively). Using e.g. sqlite this query works as expected:

```
sqlite> SELECT c1.ID, c1.CITY, c2.COUNTRY FROM cities AS c1 JOIN countries AS c2 ON c1.COUNTRY_ID = c2.ID;
1|Hamburg|Germany
2|Stockholm|Sweden
3|Osaka|Japan
4|Berlin|Germany
5|Göteborg|Sweden
6|Tokyo|Japan
7|Kyoto|Japan
```

Tested on `0.3.4` and `main+gf72299f`.

**Comment by houqp** [comment] 2021-09-18 19:13
Thanks @johanols for the detailed bug report! This is caused by https://github.com/apache/arrow-datafusion/blob/db305dadea458a26723fa53d85463155247d39f9/datafusion/src/physical_plan/hash_utils.rs#L92. From a quick glance, it looks like we are indeed being too strict on join conditions. I will work on a fix for it this weekend.

**Comment by houqp** [comment] 2021-09-19 23:55
This should be addressed by https://github.com/apache/arrow-datafusion/pull/1023

**Closed** 2021-09-20 03:50 UTC
Labels: bug

**Comment by houqp** [comment] 2021-09-20 05:05
FYI, cutting a 0.4.1 release to pick up this fix.

**Comment by johanols** [comment] 2021-09-23 22:17
Wow! That was fast! 😲
Just tried it out with the 0.4.1 release. Works like a charm 👍
Thank you!
