### ISSUE TITLE
“docker run” doesn't work，just exit 

### ISSUE THREAD

**Issue by sultra** [roapi/roapi#188] opened 2022-08-28 14:10 UTC
follow the readme guide and "use docker" part

``` shell
docker run -t --rm -p 8080:8080 ghcr.io/roapi/roapi:latest --addr-http 0.0.0.0:8080 \
    --table "uk_cities=test_data/uk_cities_with_headers.csv" \
    --table "test_data/spacex_launches.json"

```
in Ubuntu 20.04.4，docker 20.10.17 run that scripts and doesn't work，just exit fast，no logs,no errors out，no response anymore

May I ask What I miss something with use docker running？Is enable any docker special feature？

**Comment by houqp** [comment] 2022-08-29 05:53
I am not able to reproduce this error, @sultra are you running the docker command inside a virtual machine? what is the exit code you got?

**Comment by sultra** [comment] 2022-08-30 12:44
yes, docker run in  virtual machine. there is no exit code

**Comment by houqp** [comment] 2022-09-24 15:56
This is likely the same issue as https://github.com/roapi/roapi/issues/102#issuecomment-967010769

**Comment by houqp** [comment] 2022-09-25 02:22
closing this for now, let me know if the fix in 102 doesn't work for you.

**Closed by houqp** 2022-09-25 02:22 UTC
