### ISSUE TITLE
feature question 

### ISSUE THREAD

**Issue by cwiese** [roapi/roapi#151] opened 2022-03-03 20:43 UTC
Can we get access to the datafusion/arrow underlying data - to make updates?   This is an awesome project - however - we need to make updates and see the new queries reflect the update.

**Comment by houqp** [comment] 2022-03-09 06:06
it's all doable in theory, would be good to learn more about what kind of updates do you have in mind.

**Comment by houqp** [comment] 2022-03-10 17:49
closing this since it's a duplicate of https://github.com/roapi/roapi/issues/55 :)

**Closed by houqp** 2022-03-10 17:49 UTC
