### ISSUE TITLE
google sheets - some sheets with empty cells cause error - others do not

### ISSUE THREAD

**Issue by magick93** [roapi/roapi#140] opened 2022-02-14 04:01 UTC
I'm encountering a strange error.

I have two google sheets - and therefore two roapi tables. Both sheets have cells that are empty.

One sheet causes the below error. And this error is solved when I add a value to cells that are empty. 
The other sheet has cells that are empty (within the grid of values) and it doesnt cause any errors. 

# Error

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', columnq/src/table/google_spreadsheets.rs:196:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by houqp** [comment] 2022-02-14 04:19
Interesting, this is caused by https://github.com/roapi/roapi/blob/47a17f069647dd7e9ff2b7c721b1a2d4185d24d2/columnq/src/table/google_spreadsheets.rs#L196.

Which means the API response we got from google excluded that empty cell: https://github.com/roapi/roapi/blob/47a17f069647dd7e9ff2b7c721b1a2d4185d24d2/columnq/src/table/google_spreadsheets.rs#L335-L339

The code was written with the assumption that google spreadsheet api will return a value for every cell in the sheet. Could you help create a minimally reproducible google spreadsheet so I can try reproduce this on my end?

**Comment by magick93** [comment] 2022-02-14 04:30
You should be able view https://docs.google.com/spreadsheets/d/1V0lB_IMmYic7enOxirXYRs5AsrM5XOMXVeu9AF5efD8/edit?usp=sharing.

**Comment by magick93** [comment] 2022-02-14 04:54
I suspect it has to do with sheets that contain, or used to contain, cells that had links (href).

**Comment by magick93** [comment] 2022-02-15 03:52
Also, calculated values are not returned when calling the roapi.
See https://docs.google.com/spreadsheets/d/1rEM_BmB343nNMOOvv1ymUm2TEPmMUlvo8VSjSw-eAmM/edit#gid=1754317343

But, these columns are in the schema.

**Comment by magick93** [comment] 2022-02-15 05:34
Sorry. The last comment was definitely a mistake. Computed values are working as expected.

**Comment by houqp** [comment] 2022-02-15 05:47
```
20:26:37 ❯ curl -X POST -d "select Var from pert where Role = 'DEV'" localhost:8080/api/sql     
[{"Var":"40,000.00"}]% 
```

**Comment by houqp** [comment] 2022-02-15 05:50
The empty cell issue will be fixed in PR 141.

**Closed** 2022-02-15 06:23 UTC
